name: python lint

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
